### ISSUE TITLE
upload picture

### ISSUE THREAD

**Issue by EslemOuederni** [chingu-voyages/v44-tier3-team-33#24]
**__User Story Description__**
As a user
I want to upload a picture
So I can add my post

**__Additional Considerations__**
To save images remotely when using MongoDB, you can consider using a cloud-based storage solution such as Amazon S3.

1. Set up an Amazon S3 bucket and credentials. You can create a new bucket and IAM user with the necessary permissions for your application to access the bucket.
2. Install the `aws-sdk` package in your Node.js application
3. Install multer to handle uploading images

**Comment by khaledtf19** [comment]
we don't need that I already did that on the post form 
here #29
